### ISSUE TITLE
Question. How to set up the SMTP server using this suit 

### ISSUE THREAD

**Issue by gizmochief7** [blacklabelops/atlassian#1]
Im running CentOS 7. I have ran and successfully setup this project and have all applications contained within it running and synced together. However I cant figure out how to set up the SMTP server used for email. Do you use NGINX or Jenkins or maybe Is there a argument i should be passing in. Everything is secured with letsencript.

**Comment by blacklabelops** [comment]
Hello Gizmo! The mailservers settings must be configured inside the administration settings page of each application separately! E.g. crowd, jira, confluence and bitbucket. There is no mechanism to do this with environment variables.

The mail server communication is outbound communication. All applications should have no problems sending outgoing emails.

**Comment by gizmochief7** [comment]
Thanks for the reply and thanks for making this stack! I saw where to configure the mail in each application but I didn't know if you had a service container that ran a SMTP host that could pointed to. Gmail limits my email address but for now i just configured it to use smtp.gmail.com as the host. Your suggestions does answer my question. 

As a follow up question. I modified your docker-compose.yml file in hopes of adding your Jenkins to the stack. However, I'm having some problems with making it a clean integration as you have done with the current Atlassian Stack. I wanted to show you my changes and hopefully get some help setting this up. Would this be something you could do and if so should I open up a new issue or ask it here?

**Comment by blacklabelops** [comment]
Add this to your env file:

~~~~
#Cloudbees Container Settings
export CLOUDBEES_JENKINS_DOMAIN_NAME=jenkins.yourhost.com
export CLOUDBEES_JENKINS_JAVA_OPTIONS=-Xmx2048m -Xms512m
~~~~

Add this to the services section of the docker-compose stack file:

~~~~
  jenkins:
    image: blacklabelops/jenkins:alpine.2.32.3
    hostname: jenkins
    volumes:
      - jenkins_data:/jenkins
    environment:
      - 'TZ=${ATLASSIAN_TIME_ZONE}'
      - 'JAVA_VM_PARAMETERS=${CLOUDBEES_JENKINS_JAVA_OPTIONS}'
    restart: unless-stopped
~~~~

Add this to the volumes section in the docker-compose stack file:

~~~~
jenkins_data:
    external: false
~~~~

Adjust nginx container definition to the following:

~~~~
nginx:
    image: blacklabelops/nginx:${ATLASSIAN_NGINX_VERSION}
    ports:
      - '443:443'
      - '80:80'
    networks:
      default:
        aliases:
          - '${CONFLUENCE_DOMAIN_NAME}'
          - '${CROWD_DOMAIN_NAME}'
          - '${BITBUCKET_DOMAIN_NAME}'
          - '${JIRA_DOMAIN_NAME}'
          - '${CLOUDBEES_JENKINS_DOMAIN_NAME}'
    volumes:
      - nginx_volume:/home/nginx
      - ssl_certificates:/etc/letsencrypt
    environment:
      - 'TZ=${ATLASSIAN_TIME_ZONE}'
      - 'NGINX_REDIRECT_PORT80=${ATLASSIAN_PORT80_REDIRECT}'
      - 'SERVER1SERVER_NAME=${JIRA_DOMAIN_NAME}'
      - 'SERVER1REVERSE_PROXY_LOCATION1=/'
      - 'SERVER1REVERSE_PROXY_PASS1=http://jira:8080'
      - 'SERVER1HTTPS_ENABLED=${ATLASSIAN_HTTPS}'
      - 'SERVER1HTTP_ENABLED=${ATLASSIAN_HTTP}'
      - 'SERVER1LETSENCRYPT_CERTIFICATES=${ATLASSIAN_HTTPS}'
      - 'SERVER1CERTIFICATE_FILE=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER1CERTIFICATE_KEY=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/privkey.pem'
      - 'SERVER1CERTIFICATE_TRUSTED=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER1PROXY_APPLICATION=jira'
      - 'SERVER2SERVER_NAME=${CROWD_DOMAIN_NAME}'
      - 'SERVER2REVERSE_PROXY_LOCATION1=/'
      - 'SERVER2REVERSE_PROXY_PASS1=http://crowd:8095'
      - 'SERVER2HTTPS_ENABLED=${ATLASSIAN_HTTPS}'
      - 'SERVER2HTTP_ENABLED=${ATLASSIAN_HTTP}'
      - 'SERVER2LETSENCRYPT_CERTIFICATES=${ATLASSIAN_HTTPS}'
      - 'SERVER2CERTIFICATE_FILE=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER2CERTIFICATE_KEY=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/privkey.pem'
      - 'SERVER2CERTIFICATE_TRUSTED=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER2PROXY_APPLICATION=crowd'
      - 'SERVER3SERVER_NAME=${CONFLUENCE_DOMAIN_NAME}'
      - 'SERVER3REVERSE_PROXY_LOCATION1=/synchrony'
      - 'SERVER3REVERSE_PROXY_PASS1=http://confluence:8091'
      - 'SERVER3REVERSE_PROXY_APPLICATION1=confluence6'
      - 'SERVER3REVERSE_PROXY_LOCATION2=/'
      - 'SERVER3REVERSE_PROXY_PASS2=http://confluence:8090'
      - 'SERVER3REVERSE_PROXY_APPLICATION2=confluence'
      - 'SERVER3HTTPS_ENABLED=${ATLASSIAN_HTTPS}'
      - 'SERVER3HTTP_ENABLED=${ATLASSIAN_HTTP}'
      - 'SERVER3LETSENCRYPT_CERTIFICATES=${ATLASSIAN_HTTPS}'
      - 'SERVER3CERTIFICATE_FILE=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER3CERTIFICATE_KEY=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/privkey.pem'
      - 'SERVER3CERTIFICATE_TRUSTED=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER3PROXY_APPLICATION=confluence'
      - 'SERVER4SERVER_NAME=${BITBUCKET_DOMAIN_NAME}'
      - 'SERVER4REVERSE_PROXY_LOCATION1=/'
      - 'SERVER4REVERSE_PROXY_PASS1=http://bitbucket:7990'
      - 'SERVER4HTTPS_ENABLED=${ATLASSIAN_HTTPS}'
      - 'SERVER4HTTP_ENABLED=${ATLASSIAN_HTTP}'
      - 'SERVER4LETSENCRYPT_CERTIFICATES=${ATLASSIAN_HTTPS}'
      - 'SERVER4CERTIFICATE_FILE=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER4CERTIFICATE_KEY=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/privkey.pem'
      - 'SERVER5SERVER_NAME=${CLOUDBEES_JENKINS_DOMAIN_NAME}'
      - 'SERVER5REVERSE_PROXY_LOCATION1=/'
      - 'SERVER5REVERSE_PROXY_PASS1=http://jenkins:8080'
      - 'SERVER5HTTPS_ENABLED=${ATLASSIAN_HTTPS}'
      - 'SERVER5HTTP_ENABLED=${ATLASSIAN_HTTP}'
      - 'SERVER5LETSENCRYPT_CERTIFICATES=${ATLASSIAN_HTTPS}'
      - 'SERVER5CERTIFICATE_FILE=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER5CERTIFICATE_KEY=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/privkey.pem'
      - 'SERVER4CERTIFICATE_TRUSTED=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER4PROXY_APPLICATION=jenkins'
    restart: unless-stopped
~~~~

**Comment by blacklabelops** [comment]
Example of adding a Jenkins slave:

~~~~
# Jenkins Slaves
  java_jenkins_slave:
    image: blacklabelops/swarm-jdk8
    environment:
      - 'TZ=${ATLASSIAN_TIME_ZONE}'
      - 'SWARM_CLIENT_EXECUTORS=2'
      - 'SWARM_CLIENT_LABELS=java8'
      - 'SWARM_CLIENT_NAME=JavaJDK8'
      - 'SWARM_VM_PARAMETERS=-Xmx512m -Xms256m'
      - 'SWARM_MASTER_URL=http://jenkins:8080/'
      - 'SWARM_JENKINS_USER=YOUR_JENKINS_USER'
      - 'SWARM_JENKINS_PASSWORD=YOUR_JENKINS_PASSWORD'
    restart: unless-stopped
~~~~

**Comment by gizmochief7** [comment]
Sorry for the few days that past without giving you feedback on this. I was having a crowd issue. Thanks for that awesome example that worked great for getting Jenkins up and running with the compose file. I added what you said, and then I added `- 'LETSENCRYPT_DOMAIN5=${CLOUDBEES_JENKINS_DOMAIN_NAME}'` to my dc-letsencrypt.yml to get https working. Here I tried to shut down the NGINX container since it was bound to 443 and run the letsencrypt command. This failed each time because another container was bound to it. Trying something different, I just ran `docker-compose stop` on the whole stack and then `docker-compose up -d`. Then I ran `docker-compose -f dc-letsencrypt.yml run --rm -p 443:443 letsencrypt install`. However Jenkins is still unsecure showing https as not working. I can still get to https://jenkins.myHost.com but the https part shows as not working. However, this led to a bigger problem that I had to solve the last time I shut everything down with compose. My Crowd application wont let me log in with any user. If i put in an invalid pw, crowd will show that its invalid. if i put in the right pw it will error out saying "Connection to authentication server failed. Please review the logs for more information." Whats really strange is that i can still authenticate to with crowd into JIRA, Confluence, and Bitbucket. It seems that each time i shut the stack down this way is causing my crowd application to do this same thing. Last time, i was only able to recover from this by stopping/removing the crowd container, deleting its postgresql data base, removing its volume, starting clean start crowd container and restored it from a backup xml you that you started for me (Thanks for that). This as a work-a-round is a little time consuming each time. 

Is there a better way to add lets encrypt to the compose file for Jenkins? 
Also is there a better way to restart the stack where my crowd doesn't get hosed each time? 

Please ask more questions if needed.
Thanks
Justin

>

**Comment by blacklabelops** [comment]
Certificate issue:
- You have to recreate the certificates when you add a new domain
- Check letsencrypt logs for successfull certificate generation
- Check letsencrypt volume that there is a new certificate folder and its creation date
- Check nginx log for errors

Port issue:
- Check for any container that this hold port 80 or 443
- Check running docker proxy process instances that still acquire port 80 or 443
- Make sure you removed the letsencrypt container after generating the certificates

Crowd:
- Check jira logs when logging in
- Check crowd logs when logging in

General:
- Check that crowd configuration is correct.
- Check that application links work.
- Check that all application links are accepted by crowd

And add more detail information like log errors when reporting issues.

**Comment by gizmochief7** [comment]
Your original answer solved the initial issue I was having. Thanks
